# Generated by Django 4.2 on 2023-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="create_time",
            new_name="create_times",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="update_time",
            new_name="update_times",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="create_time",
            new_name="create_times",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="update_time",
            new_name="update_times",
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_delete",
            field=models.BooleanField(default=True, verbose_name="删除标记"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_delete",
            field=models.BooleanField(default=True, verbose_name="删除标记"),
        ),
    ]
